# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
#
# copied from ripgrep, see: https://github.com/BurntSushi/ripgrep/pull/1613

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# [env]
# CI_PKG_VERSION_PRE_RELEASE = "alphabeta"
# CI_PKG_VERSION_BUILD = "1234"
